import sys, os
sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "..")))
import streamlit as st
import pandas as pd
from frontend.api_client import get_alerts

st.title("🚨 Fraud Alerts Console")
st.caption("Review, investigate and resolve fraud alerts generated by all detection engines")
st.divider()

col1, col2, col3 = st.columns(3)
with col1:
    status_filter = st.selectbox("Filter by Status", ["All", "NEW", "UNDER_INVESTIGATION", "RESOLVED_BLOCKED", "RESOLVED_FALSE_POSITIVE"])
with col2:
    limit = st.slider("Max Alerts", 10, 200, value=50)
with col3:
    st.write("")
    refresh = st.button("🔄 Refresh Alerts", use_container_width=True)

status = None if status_filter == "All" else status_filter
alerts_data = get_alerts(limit=limit, status=status)

if isinstance(alerts_data, dict) and "error" in alerts_data:
    st.error(f"Failed to load alerts: {alerts_data['error']}")
    st.stop()

if not isinstance(alerts_data, list) or len(alerts_data) == 0:
    st.info("No fraud alerts found. Run transaction scans or fusion assessments to generate alerts.")
    st.stop()

# KPI row
total = len(alerts_data)
high_count = sum(1 for a in alerts_data if a.get("risk_level") == "HIGH")
new_count = sum(1 for a in alerts_data if a.get("status") == "NEW")
resolved = sum(1 for a in alerts_data if "RESOLVED" in a.get("status", ""))

m1, m2, m3, m4 = st.columns(4)
m1.metric("Total Alerts", total)
m2.metric("HIGH Risk", high_count)
m3.metric("Unresolved (NEW)", new_count)
m4.metric("Resolved", resolved)

st.divider()

rows = []
for a in alerts_data:
    rows.append({
        "Alert ID": a.get("alert_id", ""),
        "Event Type": a.get("event_type", ""),
        "Risk Score": a.get("risk_score", 0),
        "Risk Level": a.get("risk_level", ""),
        "Status": a.get("status", ""),
        "Top Reason": (a.get("reasons") or ["—"])[0][:80],
        "Timestamp": str(a.get("created_at", ""))[:19]
    })

df = pd.DataFrame(rows)

def color_risk(val):
    c = {"HIGH": "color: #e74c3c; font-weight:bold", "MEDIUM": "color: #f39c12; font-weight:bold", "LOW": "color: #27ae60"}
    return c.get(val, "")

def color_status(val):
    c = {"NEW": "color: #e74c3c", "UNDER_INVESTIGATION": "color: #f39c12", "RESOLVED_BLOCKED": "color: #27ae60", "RESOLVED_FALSE_POSITIVE": "color: #95a5a6"}
    return c.get(val, "")

styled = df.style.applymap(color_risk, subset=["Risk Level"]).applymap(color_status, subset=["Status"])
st.dataframe(styled, use_container_width=True, height=400)

st.divider()
st.subheader("🔍 Alert Detail Viewer")
selected_id = st.selectbox("Select Alert ID to inspect", ["— Select —"] + [a.get("alert_id", "") for a in alerts_data])
if selected_id and selected_id != "— Select —":
    alert = next((a for a in alerts_data if a.get("alert_id") == selected_id), None)
    if alert:
        col_a, col_b = st.columns(2)
        with col_a:
            st.markdown(f"**Alert ID:** `{alert['alert_id']}`")
            st.markdown(f"**Event Type:** `{alert['event_type']}`")
            st.markdown(f"**Risk Score:** `{alert['risk_score']}`")
            st.markdown(f"**Risk Level:** `{alert['risk_level']}`")
            st.markdown(f"**Status:** `{alert['status']}`")
        with col_b:
            st.markdown("**Risk Reasons:**")
            for r in (alert.get("reasons") or []):
                st.caption(f"• {r}")
            st.markdown("**Recommended Actions:**")
            for a in (alert.get("recommended_action") or []):
                st.caption(f"• {a}")
